import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

import { Toaster } from '@/components/ui/sonner'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const antaFont = localFont({
  src: './fonts/Anta-Regular.ttf',
  variable: '--font-anta',
})

const kodeMono = localFont({
  src: [
    {
      path: './fonts/KodeMono-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
    {
      path: './fonts/KodeMono-SemiBold.ttf',
      weight: '600',
      style: 'semibold',
    },
    {
      path: './fonts/KodeMono-Medium.ttf',
      weight: '500',
      style: 'medium',
    },
    {
      path: './fonts/KodeMono-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-kode-mono',
})

export const metadata: Metadata = {
  title: {
    template: '%s | Black Hole Storage',
    default: 'Black Hole Storage',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${antaFont.variable} ${kodeMono.variable} min-w-screen min-h-screen bg-neutral-900 font-inter`}
      >
        {children}
      </body>
      <Toaster closeButton theme="system" />
    </html>
  )
}
